#-----Database-----
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=postgres

#-----Nats connection-----
subject=gostream.curves
host=tls://nats.geosteering.ru:4222
credentials-file=app.creds
reconnect-timeout-sec=10

#-----Message processing-----
realtime-threads=2
history-threads=6
history-request-limit=15000
history-onetime-requests=4

#-----Data storage-----
batch-size=1000
margin-size=20

#-----Scaling-----
scale-minutes={1,2,5,10,15,30,60,180,360,720,1440,10080}

#-----Logging-----
logging.file.path=logs
logging.file.name=logs/goperform-cache.log
logging.logback.rollingpolicy.file-name-pattern=logs/goperform-cache-%d{yyyy-MM-dd}.%i.log
logging.level.ru.geosteering.goperform.cache=debug
logging.level.org.springframework.security=debug
logging.level.org.springframework.web.socket=debug
logging.level.org.springframework.messaging=debug