#-----Database-----
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=postgres

#-----Nats connection-----
subject=gostream.curves
host=tls://nats.geosteering.ru:4222
credentials-file=app.creds
reconnect-timeout-sec=10

#-----Message handling-----
realtime-threads=2
history-threads=6
history-request-limit=20000
history-onetime-requests=4

#-----Data storage-----
batch-size=1000
margin-size=20


#logging.level.org.springframework.messaging=trace
#logging.level.org.springframework.web.socket=trace
#logging.level.org.springframework.messaging.simp=trace