# Web
server.http2.enabled=true
server.servlet.context-path=/cache/api
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,application/stream+json,application/xml,text/html,text/plain
spring.codec.max-in-memory-size=100MB
#
# ApiService
goperform.dataservice-baseurl=${GOSTREAM_DATA_SERVICE_URL:http://localhost:9002/api}
goperform.api-service.username=${GOSTREAM_USERNAME:alice}
goperform.api-service.password=${GOSTREAM_PASSWORD:12345}
#
# Actuator and Prometheus metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.jmx.exposure.include=health,info
management.info.env.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram."[http.server.requests]"=true
info.application.version=@application.version@
#
# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/goperform_cache}
spring.datasource.username=${DB_USR:goperform_cache}
spring.datasource.password=${DB_PSW:goperform_cache}
spring.datasource.hikari.maximum-pool-size=30
#
# NATS connection
goperform.subject=gostream.curves
goperform.auth=gostream.auth
goperform.host=${NATS_URL:nats://localhost:4222}
goperform.credentials-file=${NATS_CREDENTIALS:app.creds}
goperform.reconnect-timeout-sec=10
#
# Message processing
goperform.realtime-threads=${REALTIME_THREADS:4}
goperform.history-threads=${HISTORY_THREADS:8}
goperform.history-request-limit=${REQUEST_MESSAGES_LIMIT:15000}
goperform.nats-onetime-requests=${NATS_REQUESTS:4}
#
# Data storage
goperform.batch-size=1000
goperform.margin-size=200
#
# Scaling
goperform.scale-minutes={1,2,5,10,15,30,60,180,360,720,1440,10080}
goperform.segment-scale-min=${SEGMENT_SCALE_MIN:30}
#
# Statistic
goperform.statistic-period-sec=30
goperform.reload-period-sec=5
goperform.clear-broken-period-min=3
goperform.delete-inactive-period-hr=12
#
# Logging
logging.config=${LOG_CONFIG:classpath:logback-local.xml}
logging.graylog.host=udp:graylog.geosteering.ru
logging.graylog.port=12201
logging.graylog.source=${GRAYLOG_SOURCE:perform.geosteering.ru}
logging.app-name=GOperformCache
logging.level.ru.geosteering.goperform.cache=info
logging.level.org=error
#
# Scheduling
spring.task.scheduling.pool.size=6
#
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#
#Auto-cleaning
goperform.cleaning.curve.days=${DAYS_BEFORE_CURVE_REMOVE:30}
goperform.cleaning.processor.days=${DAYS_BEFORE_PROCESSOR_REMOVE:7}