# Web
server.http2.enabled=true
server.servlet.context-path=/cache/api

# DataService
goperform.dataservice-baseurl=${GOSTREAM_DATA_SERVICE_URL:http://localhost:9002/api}

# Actuator
management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.info.git.enabled=true
management.info.git.mode=full
management.endpoints.web.exposure.include=info

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/goperform_cache}
spring.datasource.username=${DB_USR:goperform_cache}
spring.datasource.password=${DB_PSW:goperform_cache}
spring.datasource.hikari.maximum-pool-size=30

# NATS connection
goperform.subject=gostream.curves
goperform.objects=gostream.objects
goperform.auth=gostream.auth
goperform.host=${NATS_URL:nats://localhost:4222}
goperform.nats.username=${GOSTREAM_USERNAME:alice}
goperform.nats.password=${GOSTREAM_PASSWORD:12345}
goperform.credentials-file=app.creds
goperform.reconnect-timeout-sec=10

# Message processing
goperform.realtime-threads=4
goperform.history-threads=8
goperform.history-request-limit=15000
goperform.nats-onetime-requests=4

# Data storage
goperform.batch-size=1000
goperform.margin-size=200

# Scaling
goperform.scale-minutes={1,2,5,10,15,30,60,180,360,720,1440,10080}

# Statistic
goperform.statistic-period-sec=30

# Logging
logging.config=${LOG_CONFIG:classpath:logback-local.xml}
logging.graylog.host=udp:graylog.geosteering.ru
logging.graylog.port=12201
logging.graylog.source=${GRAYLOG_SOURCE:perform.corp.geosteering.ru}
logging.app-name=GOperformCache

# Scheduling
spring.task.scheduling.pool.size=6

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#Auto-cleaning
goperform.cleaning-data.days=${DAYS_BEFORE_REMOVE:30}